### ISSUE TITLE
BUG - Batch Job Failing due to SPICE

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/imap_processing#827]
### Description of the issue

This is expected because we need to make sure infrastructure is updated with new changes from `imap_processing` SPICE work.

### Steps to reproduce the issue

upload SWE file or any instrument file.

### Actual behavior (What does happen)

**Logs from batch job:**

```
INFO:imap_processing.cli:IMAP Processing Version: 0.5.0.post14.dev0+3e9f5b4
--
INFO:imap_processing.cli:Processing Swe level l1a
INFO:imap_processing.cli:Beginning preprocessing (download dependencies)
INFO:imap_data_access.io:Querying data archive for {'instrument': 'swe', 'data_level': 'l0', 'descriptor': 'raw', 'start_date': '20240510', 'end_date': '20240510', 'version': 'v022'} with url https://api.dev.imap-mission.com/query?instrument=swe&data_level=l0&descriptor=raw&start_date=20240510&end_date=20240510&version=v022
INFO:imap_data_access.io:Downloading file imap/swe/l0/2024/05/imap_swe_l0_raw_20240510_v022.pkts from https://api.dev.imap-mission.com/download/imap/swe/l0/2024/05/imap_swe_l0_raw_20240510_v022.pkts to /app/data/imap/swe/l0/2024/05/imap_swe_l0_raw_20240510_v022.pkts
INFO:imap_processing.cli:Beginning actual processing
INFO:space_packet_parser.parser:Creating packet generator from a filelike object, <_io.BufferedReader name='/app/data/imap/swe/l0/2024/05/imap_swe_l0_raw_20240510_v022.pkts'>. Total length is 37526 bytes
Processing SWE l1a
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/imap_processing/spice/kernels.py", line 134, in wrapper_ensure_spice
return func(
^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/spice/time.py", line 70, in _sct2e_wrapper
return np.array([spice.sct2e(IMAP_SC_ID, s) for s in sclk_ticks])
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/spiceypy/spiceypy.py", line 139, in with_errcheck
check_for_spice_error(f)
File "/usr/local/lib/python3.12/site-packages/spiceypy/spiceypy.py", line 122, in check_for_spice_error
raise dynamically_instantiate_spiceyerror(
spiceypy.utils.exceptions.SpiceKERNELVARNOTFOUND:
================================================================================
Toolkit version: CSPICE_N0067
SPICE(KERNELVARNOTFOUND) --
The Variable Was not Found in the Kernel Pool.
Kernel variable SCLK_DATA_TYPE_43 was not found in the kernel pool.
sct2e_c --> SCT2E --> SCTYPE --> SCTY01
================================================================================
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/bin/imap_cli", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/cli.py", line 855, in main
instrument.process()
File "/usr/local/lib/python3.12/site-packages/imap_processing/cli.py", line 341, in process
products = self.do_processing(dependencies)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/cli.py", line 768, in do_processing
datasets = [swe_l1a(str(dependencies[0]), data_version=self.version)]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/swe/l1a/swe_l1a.py", line 41, in swe_l1a
datasets_by_apid = packet_file_to_datasets(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/utils.py", line 386, in packet_file_to_datasets
time_data = met_to_j2000ns(data[time_key])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/spice/time.py", line 44, in met_to_j2000ns
return np.asarray(_sct2e_wrapper(sclk_ticks) * 1e9, dtype=np.int64)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/imap_processing/spice/kernels.py", line 157, in wrapper_ensure_spice
raise SpiceyError(
spiceypy.utils.exceptions.SpiceyError:
================================================================================
Toolkit version: CSPICE_N0067
When calling a function requiring SPICE, we failedto load a metakernel. SPICE_METAKERNEL is not set,and time_kernels_only is not set to True --
================================================================================


```

### Code Snippet:

```python
Code
```

**Comment by greglucas** [comment]
@tech3371 was this closed by your update?

**Comment by tech3371** [comment]
yes
